// ==============================================================================
// SMILEX BIKE - TELEGRAM WEBHOOK (RECEIVES ADMIN REPLIES FROM TELEGRAM TOPICS)
// ==============================================================================

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(200).send('Telegram Webhook Active');
  }

  try {
    const update = req.body;
    const msg = update.message;

    if (msg && msg.text) {
      const threadId = msg.message_thread_id;
      const text = msg.text;
      const fromBot = msg.from?.is_bot;

      // Ignore messages generated by the bot itself to prevent echo loop
      if (!fromBot && threadId) {
        const sessionId = global._topicToSession?.get(String(threadId));
        if (sessionId) {
          const session = global._sessionStore?.get(sessionId);
          if (session) {
            const adminMsg = {
              sender: 'admin',
              text: text,
              author: msg.from?.first_name || 'Admin',
              time: new Date().toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' })
            };
            session.messages.push(adminMsg);
            console.log(`[Admin Reply to ${sessionId}]:`, text);
          }
        }
      }
    }

    return res.status(200).json({ ok: true });
  } catch (err) {
    console.error('Telegram Webhook error:', err);
    return res.status(200).json({ ok: true });
  }
}
